### ISSUE TITLE
API endpoint 'search' - how to retrieve paginated results

### ISSUE THREAD

**Issue by kp14** [EBISPOT/OXO#25]
Hi,

when using the API 'search' endpoint using the following parameters retrieves the first page of the expected results:
    'inputSource': 'efo'
    'mappingTarget': ['MONDO']
    'distance': 1

At the end of the returned JSON, the links are listed as follows:

===snip===
"_links" : {
    "first" : {
      "href" : "https://www.ebi.ac.uk/spot/oxo/api/search?page=0&size=20"
    },
    "self" : {
      "href" : "https://www.ebi.ac.uk/spot/oxo/api/search"
    },
    "next" : {
      "href" : "https://www.ebi.ac.uk/spot/oxo/api/search?page=1&size=20"
    },
    "last" : {
      "href" : "https://www.ebi.ac.uk/spot/oxo/api/search?page=150&size=20"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 3011,
    "totalPages" : 151,
    "number" : 0
  }
}
===end===

However, I was not able to retrieve the next page of results using the link 'next'. It just gives an error and I am not surprised as the URL does not contain any query ID or similar that would tie it to the query I posted before.

Is the URL--or am I--missing something? Am I supposed to modify the URL in some way?

I would be grateful for any pointers you might be able to give me.

Regards,
Klemens

**Comment by LLTommy** [comment]
Hey kp14,

Something wrong with the links here. Yes you are supposed to follow the 'next' link, but it will not work in this case. As a workaround you could try to change paging yourself (e.g.: https://www.ebi.ac.uk/spot/oxo/api/search?inputSource=efo&mappingTarget=doid&distance=1&page=2) - I never used the search endpoint this way so make sure it works. I usually search for a certain term using the search endpoint and don't try to get all mappings .... because ...  

...if you are interested in EFO-MONDO mappings, you are able to download those from the page itself. Go to oxo, "Jump to datasource", pick EFO. On the next page, click on the bar in the graph that represents the EFO-MONDO mappings. On the next page, find the Download button in the right corner.

**Comment by kp14** [comment]
Hi LLTommy,

I hadn't noticed that I could just download all the mappings using the way you described it. Thanks for pointing this out! This might be the easiest way for me to get the data I want. The API workaround you provided seems to work, too. 

Thanks for your help.
From my point of view, this issue is resolved as I now know how to get the data. You might still want to fix those URLs though :-)

Klemens

Klemens

**Comment by simonjupp** [comment]
You just need to POST the original search request to the URL in the next link to get the next page. 

If you are getting lots of mappings with `/search` you should increase the page size (about 100 usually works quite well)

**Comment by kp14** [comment]
OK, that was not obvious to me. I think I expected the results to retrievable via a GET using the next. Thanks for clearing up my misunderstanding.
