### ISSUE TITLE
Ontology mapping not found in OxO

### ISSUE THREAD

**Issue by FuqiX** [EBISPOT/OXO#45]
Dear OxO,

I am looking for ontology mapping for term `Covid-19`, [MONDO:0100096](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096)  in OxO. 

OxO found no mapping for this term. However, according to [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096), MONDO has mapped this term to DOID:0080600  I am not sure why the DOID term didn't come out in my OxO search. Could you please help me out? Thanks.

Below is the  OxO query I used
```
curl 'https://www.ebi.ac.uk/spot/oxo/api/search' -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{
  "ids" : [ "MONDO:0100096" ],
  "inputSource" : null,
  "mappingTarget" : [ "DOID" ],
  "mappingSource" : [ "DOID","MONDO"],
  "distance" : 1
}'
```

**Comment by henrietteharmse** [comment]
There is some lag between OLS updates and OxO updates. That is the update first needs to become available on OLS and then OxO will query OLS to get the updates when the OxO data release runs. I thought this issue is related to this lag. But I have just now done a data release for OxO and it did not pick this mapping up. We will need to investigate.

**Comment by henrietteharmse** [comment]
This has now been resolved. See below screenshot.
![image](https://user-images.githubusercontent.com/32327979/99507667-95732680-297b-11eb-8cd7-cf703b6a0ee1.png)
